name: prompt-and-paint

services:
  redis:
    image: redis:7.4-rc-alpine
    volumes:
      - redis-data:/data


  go:
    build: .
    image: vmporuri/prompt-and-paint
    env_file: "secrets.env"
    depends_on:
      - redis

volumes:
  redis-data:
