name: prompt-and-paint

services:
  haproxy:
    image: haproxy:3.0-alpine
    ports:
      - "8080:80"
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy

  redis:
    image: redis:7.4-rc-alpine

  go:
    build: .
    image: vmporuri/prompt-and-paint
    depends_on:
      - haproxy
      - redis
